/*상품 코드 별 매출액 = 판매가 * 판매량*/
SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE OS
ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC,
P.PRODUCT_CODE ASC